name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04   # Change from ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - run: npx playwright install --with-deps
@v4
        with:
          name: playwright-report
          path: playwright-report